pages:
  image: debian:bookworm
  script:
    - apt-get update
    - apt-get install -y git
    - git submodule update --init --recursive
    - scripts/onion-mkdocs-provision-build
    - make onion-mkdocs-compile
  artifacts:
    paths:
      - public
  #only:
  #  - main
