#
# Onion Mkdocs configuration
#

# Inherit the base config
# Check https://github.com/mkdocs/mkdocs/blob/master/docs/user-guide/configuration.md#configuration-inheritance
INHERIT: vendors/onion-mkdocs/onion-mkdocs.yml

site_name: The Onion Plan
repo_url : https://gitlab.torproject.org/tpo/onion-services/onionplan/
edit_uri : ''

plugins:
  awesome-pages:
    collapse_single_pages: true

  redirects:
   redirect_maps:
     '0 - Introduction/Challenges.md'                                        : 'preamble/challenges.md'
     '0 - Introduction/Research.md'                                          : 'preamble/research.md'
     '0 - Introduction/Timeline.md'                                          : 'preamble/timeline.md'
     '1 - Proposals/Usability/Certification.md'                              : 'proposals/usability/certificates.md'
     '1 - Proposals/Usability/Discovery/Address-Translation.md'              : 'proposals/usability/discovery/translation.md'
     '1 - Proposals/Usability/Discovery/Onion-Names.md'                      : 'proposals/usability/discovery/onion-names.md'
     '1 - Proposals/Usability/Discovery/README.md'                           : 'proposals/usability/discovery/README.md'
     '1 - Proposals/Usability/README.md'                                     : 'proposals/usability/README.md'
     '2 - Roadmaps/01 - Roadmap: Network Layer Proposal.md'                  : 'scenarios/network.md'
     '2 - Roadmaps/01 - Roadmap: Health Proposal.md'                         : 'scenarios/network.md'
     '2 - Roadmaps/02 - Roadmap: Usability Proposal - Certificates.md'       : 'scenarios/certificates.md'
     '2 - Roadmaps/03 - Roadmap: Usability Proposal - Service Discovery.md'  : 'scenarios/discovery.md'
     '2 - Roadmaps/04 - Roadmap: Usability Proposal - Other Improvements.md' : 'scenarios/ux.md'
     '2 - Roadmaps/05 - Roadmap: Outreach.md'                                : 'scenarios/outreach.md'
     '2 - Roadmaps/06 - Roadmap: Applications.md'                            : 'scenarios/applications.md'
     '2 - Roadmaps/06 - Roadmap: Tooling.md'                                 : 'scenarios/applications.md'
     '3 - Appendixes/01 - Appendix: Proposal 279 fixes and improvements.md'  : 'appendixes/prop279.md'
     '3 - Appendixes/02 - Appendix: Specs for DNS-based .onion records.md'   : 'appendixes/dns.md'
     '3 - Appendixes/03 - Appendix: Low-hanging fruit.md'                    : 'appendixes/low-hanging.md'
     '4 - About/CREDITS.md'                                                  : 'about/credits.md'
     '4 - About/Contact.md'                                                  : 'about/contact.md'
     '4 - About/LICENSE.md'                                                  : 'about/license.md'
     'roadmaps/applications.md'                                              : 'scenarios/applications.md'
     'roadmaps/certificates.md'                                              : 'scenarios/certificates.md'
     'roadmaps/discovery.md'                                                 : 'scenarios/discovery.md'
     'roadmaps/network.md'                                                   : 'scenarios/network.md'
     'roadmaps/outreach.md'                                                  : 'scenarios/outreach.md'
     'roadmaps/ux.md'                                                        : 'scenarios/ux.md'
     'roadmaps/other.md'                                                     : 'scenarios/ux.md'
     'intro/challenges.md'                                                   : 'preamble/challenges.md'
     'intro/research.md'                                                     : 'preamble/research.md'
     'intro/timeline.md'                                                     : 'preamble/timeline.md'
