#
# Mkdocs configuration
#

site_name: The Onion Plan
docs_dir : docs
site_dir : public
repo_url : https://gitlab.torproject.org/tpo/onion-services/onionplan/
edit_uri : ''

# Site address is bind to 0.0.0.0 so it works find inside a Docker container.
# A better config would be desirable.
#dev_addr : '0.0.0.0:8031'

theme:
  name               : material
  collapse_navigation: true
  titles_only        : false
  #logo: assets/onion-services.png
  logo: assets/tor-logo1x.png
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  # Do not use external fonts
  # Useful for offline operation, GDPR compliance and privacy in general
  # May be replaced in the future by the built-in privacy plugin
  # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#autoloading
  #     https://squidfunk.github.io/mkdocs-material/setup/ensuring-data-privacy/#built-in-privacy-plugin
  font: false

extra_css:
  - site.css

plugins:
  - search

  - awesome-pages:
      collapse_single_pages: true

  - redirects:
     redirect_maps:
       '0 - Introduction/Challenges.md'                                        : 'intro/challenges.md'
       '0 - Introduction/Research.md'                                          : 'intro/research.md'
       '0 - Introduction/Timeline.md'                                          : 'intro/timeline.md'
       '1 - Proposals/Usability/Certification.md'                              : 'proposals/usability/certificates.md'
       '1 - Proposals/Usability/Discovery/Address-Translation.md'              : 'proposals/usability/discovery/translation.md'
       '1 - Proposals/Usability/Discovery/Onion-Names.md'                      : 'proposals/usability/discovery/onion-names.md'
       '1 - Proposals/Usability/Discovery/README.md'                           : 'proposals/usability/discovery/README.md'
       '1 - Proposals/Usability/README.md'                                     : 'proposals/usability/README.md'
       '2 - Roadmaps/01 - Roadmap: Network Layer Proposal.md'                  : 'roadmaps/network.md'
       '2 - Roadmaps/01 - Roadmap: Health Proposal.md'                         : 'roadmaps/network.md'
       '2 - Roadmaps/02 - Roadmap: Usability Proposal - Certificates.md'       : 'roadmaps/certificates.md'
       '2 - Roadmaps/03 - Roadmap: Usability Proposal - Service Discovery.md'  : 'roadmaps/discovery.md'
       '2 - Roadmaps/04 - Roadmap: Usability Proposal - Other Improvements.md' : 'roadmaps/other.md'
       '2 - Roadmaps/05 - Roadmap: Outreach.md'                                : 'roadmaps/outreach.md'
       '2 - Roadmaps/06 - Roadmap: Applications.md'                            : 'roadmaps/applications.md'
       '2 - Roadmaps/06 - Roadmap: Tooling.md'                                 : 'roadmaps/applications.md'
       '3 - Appendixes/01 - Appendix: Proposal 279 fixes and improvements.md'  : 'appendixes/prop279.md'
       '3 - Appendixes/02 - Appendix: Specs for DNS-based .onion records.md'   : 'appendixes/dns.md'
       '3 - Appendixes/03 - Appendix: Low-hanging fruit.md'                    : 'appendixes/low-hanging.md'
       '4 - About/CREDITS.md'                                                  : 'about/credits.md'
       '4 - About/Contact.md'                                                  : 'about/contact.md'
       '4 - About/LICENSE.md'                                                  : 'about/license.md'
       'roadmaps/other.md'                                                     : 'docs/roadmaps/ux.md'

markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2023 The Tor Project Inc. See LICENSE for details.

extra:
  generator: false
