#
# Mkdocs configuration
#

site_name: The Onion Plan
docs_dir : docs
site_dir : public
repo_url : https://gitlab.torproject.org/tpo/onion-services/onionplan/

# Site address is bind to 0.0.0.0 so it works find inside a Docker container.
# A better config would be desirable.
#dev_addr : '0.0.0.0:8031'

theme:
  name               : material
  collapse_navigation: true
  titles_only        : false
  #logo: assets/onion-services.png    
  logo: assets/tor-logo1x.png    

extra_css:
  - site.css

plugins:
  - search

markdown_extensions:
  - footnotes
  - pymdownx.tasklist:
      custom_checkbox: true

copyright: Copyright &copy; 2022 The Tor Project Inc. See LICENSE for details.

extra:
  generator: false
