#!/bin/bash
#
# Provisioner for the building environment.
#

# Basic dependencies
DEPENDENCIES="make mkdocs python3-pip"

# PyPI dependencies
DEPENDENCIES_PIP="mkdocs-material mkdocs-redirects mkdocs-awesome-pages-plugin"

# Check for sudo
if [ "`whoami`" != "root" ]; then
  SUDO="sudo"
fi

# Ensure an up-to-date system
$SUDO apt-get update && $SUDO apt-get dist-upgrade -y && \
  $SUDO apt-get autoremove -y && $SUDO apt-get clean

# Install dependencies
$SUDO apt install -y $DEPENDENCIES || exit 1

# Try to install twice since the --break-system-packages is a new option.
# This approach needs to be replaced by venv at some point:
# https://gitlab.torproject.org/rhatto/onion-mkdocs/-/issues/1
pip3 install $DEPENDENCIES_PIP || pip3 install --break-system-packages $DEPENDENCIES_PIP || exit 1
