#!/bin/bash
#
# Provisioner for the building environment.
#

# Basic dependencies
DEPENDENCIES="make mkdocs python3-pip"

# PyPI dependencies
DEPENDENCIES_PIP="mkdocs-material mkdocs-redirects mkdocs-awesome-pages-plugin"

# Check for sudo
if [ "`whoami`" != "root" ]; then
  SUDO="sudo"
fi

# Ensure an up-to-date system
$SUDO apt-get update && $SUDO apt-get dist-upgrade -y && \
  $SUDO apt-get autoremove -y && $SUDO apt-get clean

# Install dependencies
$SUDO apt install -y $DEPENDENCIES || exit 1

# Install python dependencies
pip3 install $DEPENDENCIES_PIP || exit 1
