#!/usr/bin/env bash
#
# Inotify builder
#

# Parameters
BASENAME="`basename $0`"
DIRNAME="$(cd `dirname $0` &> /dev/null && pwd)"
BASEDIR="$DIRNAME/.."
WATCHED="docs"

# Got to the base folder
cd $BASEDIR

# Dispatch
while inotifywait -r $WATCHED; do
  #make compile
  kvmx ssh make -C /srv/shared compile
done
